### ISSUE TITLE
Can one call an endpoint like one can with the other starter pack?

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/starter-pack-rasa-stack#1]
In the [NLU starter pack project](https://github.com/RasaHQ/starter-pack-rasa-nlu#how-to-use-it), you explain how to call an endpoint to parse a query ... I was wondering if one can do it with this project too... I have tried to use the same url as in the other project, but it doesn't work. I also tried with the url in `endpoints.yml` and no success either.

Thanks in advance

**Comment by JustinaPetr** [comment]
Hey @jahirfiquitiva. If you want to parse the Rasa Core using http requests, you can do it using the following steps:
- After you train the Rasa NLU and Rasa Core model and start the actions webhook (just like explained in this repo), you can start the Rasa Core server by running the following command:
```
python -m rasa_core.run --enable_api -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml
```
The only difference between this command and the command which is called when using _run cmdline_ is the parameter --enable_api which allows emulating the results of the model using the http requests.

- Once your assistant is loaded, you can parse the results by sending requests like the following:
```
curl -XPOST localhost:5005/conversations/default/respond -d '{"query":"hello there"}' | python -mjson.tool
```
