### ISSUE TITLE
make train-core failing

### ISSUE THREAD

**Issue by panchambanerjee** [RasaHQ/starter-pack-rasa-stack#11]
I tried to follow the instructions for the rasa-starter pack, and 'make train-core' fails with::

python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue --epochs 200
usage: train.py default [-h] [-o OUT] -d DOMAIN [--augmentation AUGMENTATION]
                        -c [CONFIG [CONFIG ...]] [--dump_stories]
                        [--debug_plots] (-s STORIES | --url URL | --core CORE)
                        [-v] [-vv] [--quiet]
train.py default: error: the following arguments are required: -c/--config
make: *** [train-core] Error 2

**Comment by JustinaPetr** [comment]
Hey @panchambanerjee  the error was due to the recent update for the Rasa Core. The repo is now updated an things should work as expected :)
