### ISSUE TITLE
sklearn_crfuit package typo

### ISSUE THREAD

**Issue by phortonssf** [RasaHQ/starter-pack-rasa-stack#15]
In requirements.txt should be 
sklearn_crfuite==0.3.6 vs sklearn_crfuit==0.3.6

**Comment by nomadavid9** [comment]
**sklearn_crfsuite==0.3.6**

**Comment by heefan** [comment]
exactly, the original doesn't work, I have to change it to `sklearn_crfsuite==0.3.6`

`macos mojave`  `python3.6.0`

**Comment by AlexAbraham1** [comment]
Also the following packages should be updated:

requests~=2.20
rasa_core_sdk~=0.12.0

**Comment by JustinaPetr** [comment]
True. This should be fixed now :)
