### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by santannamv** [RasaHQ/starter-pack-rasa-stack#16]
Using:
Rasa Core 12.2
Rasa NLU 13.8
Python 3.6
Windows 10

Please, I am trying to train the model in weatherbot tutorial and I am getting this error on CMD:

Traceback (most recent call last): File “nlu_model.py”, line 1, in from rasa_nlu.converters import load_data ModuleNotFoundError: No module named ‘rasa_nlu.converters’

Anything else I should inform here?

**Comment by wochinge** [comment]
Please ask the question in the repository of the weatherbot tutorial (https://github.com/JustinaPetr/Weatherbot_Tutorial) or in the [Rasa forum](https://forum.rasa.com). In general I guess that you are using the wrong NLU version for the tutorial.
