### ISSUE TITLE
Conversation logs

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/starter-pack-rasa-stack#2]
Hello

I am wondering where the conversation logs are located. I already tried looking into `rasa_core.log` but it contains only internal code related logs.

I would like to have the conversation logs like:
```md
- Hello (user)
- How are you? (bot)
- I'm good (user)
...
```

Something like that. Is it possible? If so, how can it be achieved? Thanks in advance!

**Comment by wochinge** [comment]
By default they are only stored in-memory. To use different tracker stores please see https://rasa.com/docs/core/tracker_stores/
