### ISSUE TITLE
No matching distribution found for tensorflow==1.10.0 (from -r requirements.txt (line 12))

### ISSUE THREAD

**Issue by blackcat69** [RasaHQ/starter-pack-rasa-stack#22]
Getting error on installing requirements.txt file:

"Could not find a version that satisfies the requirement tensorflow==1.10.0 (from -r requirements.txt (line 12)) (from versions: )
No matching distribution found for tensorflow==1.10.0 (from -r requirements.txt (line 12))"

**Comment by mahdimor** [comment]
you are probably using a newer version of python. 
see the following issue:
https://github.com/RasaHQ/rasa_core/issues/1297

**Comment by blackcat69** [comment]
Cheers dude, 3.6 it is then ... 👍
