### ISSUE TITLE
add note to install `make` to Readme

### ISSUE THREAD

**Issue by cswangjiawei** [RasaHQ/starter-pack-rasa-stack#23]
'make'is not an internal or external command, nor is it a runnable program or batch file.

**Comment by wochinge** [comment]
You have to install `make` first.
For Ubuntu the command is for example: `sudo apt-get install build-essential`, for mac you have to install the [xcode command line tools ](http://docwiki.embarcadero.com/RADStudio/Rio/en/Installing_the_Xcode_Command_Line_Tools_on_a_Mac)
