### ISSUE TITLE
make is not recognized as a command

### ISSUE THREAD

**Issue by RaminParker** [RasaHQ/starter-pack-rasa-stack#28]
Hi

I am using Windows 7.
I have installed everything via pip install -r requirements.txt

According to the tutorial on https://www.youtube.com/watch?v=lQZ_x0LRUbI&index=8&list=PL18ASZd9BEd57eQuVhm2oqifJSmqgTjQu  in the next step
 I have to start training the model. However, Anaconda Prompt does not recognizes the "make" command which is required.

Do you have any suggestions?

**Comment by MetcalfeTom** [comment]
Hey!

You can [install make on Windows](http://gnuwin32.sourceforge.net/packages/make.htm) if you want.  It's not necessary but it is a useful tool.

Alternatively you can run the make commands directly from `cmd` by just copying them from the [Makefile](https://github.com/RasaHQ/starter-pack-rasa-stack/blob/master/Makefile), for instance you can train the NLU model with the following command from the starter pack directory:

```
python -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu --project current --verbose
```
