### ISSUE TITLE
Spacy: Couldn't link model to "en"

### ISSUE THREAD

**Issue by RaminParker** [RasaHQ/starter-pack-rasa-stack#29]
In the readme file you suggest to install spacy model in the following way: python -m spacy download en

However, I get the following message:

> Error: Couldn't link to model "en". Creating a symlink in spacy/data failed. Make sure you have the required permissions and try rerunning the command as admin, or use a virtualenv. You can still import the module and call its load() method, or create symlink manually.
> ...
> ...
> Creating a shortcut link for "en" didn't work....
> Download successfully but linking failed

I am using Windows 7 and Anaconda.

I hope you can help me.

**Comment by mahdimor** [comment]
open the "anaconda cosole" as administrator ,using right click then on the
menu click on "run as administrator" ,then try again

Le ven. 4 janv. 2019 à 16:34, ParkerPeter <notifications@github.com> a
écrit :

**Comment by samrudh** [comment]
If you are on windows try opening powershell with administrator mode or try steps written in answer [here](https://stackoverflow.com/questions/53911615/not-able-to-load-english-language-module-of-spacy-with-spacy-loaden/54515094#54515094)
