### ISSUE TITLE
Where is the training data saved?

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/starter-pack-rasa-stack#3]
Hello
I wonder where the data is stored **after** training and if it's somehow readable for devs, like in a database or something.
Thanks

**Comment by jahirfiquitiva** [comment]
Yep

**Comment by JustinaPetr** [comment]
The conversations aren't saved by default at the moment. One way how you can talk to a bot and save all the conversational data in a Rasa format is using interactive learning. Check it out here: https://rasa.com/docs/core/interactive_learning/

**Comment by wochinge** [comment]
You could also a different [tracker store](https://rasa.com/docs/core/tracker_stores/) (e.g. store them in a mongodb)
