### ISSUE TITLE
prompt_toolkit incompability issue with version 2+

### ISSUE THREAD

**Issue by washcycle** [RasaHQ/starter-pack-rasa-stack#30]
Issue;

Found the latest 2+ version of prompt toolkit is not compatible.

**Workaround:**
Downgrade prompt_toolkit

pip install'prompt_toolkit==1.0.14

**References**:
https://github.com/CITGuru/PyInquirer/issues/1

**Comment by MetcalfeTom** [comment]
Thanks for the workaround!  In the next version of core, we'll be dropping `prompt-toolkit` entirely in favour of [questionary](https://github.com/tmbo/questionary) to avoid these issues (`prompt-toolkit` is no longer maintained)
