### ISSUE TITLE
run as a server and not command line

### ISSUE THREAD

**Issue by samrudh** [RasaHQ/starter-pack-rasa-stack#32]
I got rasa core  working but I want to run it as a background service.
How can I do that?

Below command can not be made as a background and it needs live connection to the computer where my rasa core is running.
`python -m rasa_core.run -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml &`

**Comment by mahdimor** [comment]
nohup python -m rasa_core.run -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml &

**Comment by bodhwani** [comment]
Hey @samrudh. How did you deploy rasa to the remote server? Can you mention any link which you have followed?

**Comment by samrudh** [comment]
> Hey @samrudh. How did you deploy rasa to the remote server? Can you mention any link which you have followed?
@bodhwani please see this [post](https://medium.com/tech-that-works/running-rasa-bot-with-aws-ec2-c08ed3b02455) which I wrote on this

**Comment by MetcalfeTom** [comment]
Hi @samrudh,

Did you fix the problem here?  You can use nohup to suppress the logs, but in order for someone to converse with the bot, there needs to be a running server
