### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by bjm88** [RasaHQ/starter-pack-rasa-stack#4]
I have tensor flow and rsa core and nlp installed properly, but doing install -r requirement.txt file fails for this 

Failed building wheel for pyyaml
  Running setup.py clean for pyyaml
Failed to build h5py scikit-learn gevent pyyaml
rasa-core 0.11.1 has requirement tensorflow<1.10,>=1.8, but you'll have tensorflow 1.10.0 which is incompatible.
awscli 1.15.79 has requirement botocore==1.10.78, but you'll have botocore 1.12.18 which is incompatible.

Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/8_/b0g1vb392ws98pthb2vcf5nr0000gn/T/pip-install-c5of845a/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/8_/b0g1vb392ws98pthb2vcf5nr0000gn/T/pip-record-8civjmc6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8_/b0g1vb392ws98pthb2vcf5nr0000gn/T/pip-install-c5of845a/h5py/

**Comment by vitormcruz** [comment]
I had the same problem and the solution was to install python 3.6 because 3.7 don't have tensor flow dependencies yet.
