### ISSUE TITLE
Custom policy in starter-pack-rasa 

### ISSUE THREAD

**Issue by bodhwani** [RasaHQ/starter-pack-rasa-stack#41]
Can we add custom policy in the starter pack, if the confidence of matching intent falls below threshold value? 
As we define action_default_fallback in Fallback policy, can we define custom action instead of default?

**Comment by MetcalfeTom** [comment]
Absolutely!  You just need to define the action name in the policy, write the code for it and include it in the `domain.yml`

[Here's the docs for it](https://rasa.com/docs/core/fallbacks/#fallback-actions)
