### ISSUE TITLE
tensorflow error DataTyle float16

### ISSUE THREAD

**Issue by liloup1789** [RasaHQ/starter-pack-rasa-stack#43]
Hello, 

when I use the command 

`make train-code`

I have the following error : 
`    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType float16 not in list of allowed values: float64, float32, complex64, complex128
make: *** [train-core] Erreur 1
`
Any clues ? 
Thanks

**Comment by MetcalfeTom** [comment]
Hi @liloup1789,

Can you post the full stacktrace please?  I want to help but I'm not sure where this was raised

**Comment by liloup1789** [comment]
hey RasaHQ/starter-pack-rasa-stack,
The problem only appears with windows. I installed Ubuntu and problem
solved. Still for winows users it is a problem

Le ven. 10 mai 2019 à 18:18, Tom Metcalfe <notifications@github.com> a
écrit :
