### ISSUE TITLE
pycrfsuite  -- error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'

### ISSUE THREAD

**Issue by smpchan** [RasaHQ/starter-pack-rasa-stack#44]
1. git clone https://github.com/RasaHQ/starter-pack-rasa-stack.git

2. cd starter-pack-rasa-stack/

3. Install Python 3.6 on Max OS (10.11.6) ; I had problem with tensorflow 1.12.0 with Python 3.7.2 so I downgrade instead and went further.

4. python3 -m pip install --upgrade pip
...
Collecting pip

  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.0.3
...

5. python3 -m pip install -r requirements.txt
Collecting jsonpickle==1.0.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ca/ce/97404d5aeb58e6155c216825c81b50f6eca8a5345c582317ae48391878f8/jsonpickle-1.0-py2.py3-none-any.whl
Collecting six==1.11.0 (from -r requirements.txt (line 3))
...
....
Collecting Twisted>=15.5 (from klein~=17.10->rasa_nlu~=0.14.4->-r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/5d/0e/a72d85a55761c2c3ff1cb968143a2fd5f360220779ed90e0fadf4106d4f2/Twisted-18.9.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/incremental/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b2/5gjvfk1j1010xptyq4gspmjm000txg/T/pip-install-a7i9hm9r/Twisted/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b2/5gjvfk1j1010xptyq4gspmjm000txg/T/pip-install-a7i9hm9r/Twisted/

6. I  fixed the CERTIFICATE_VERIFY_FAILED issue by following the advice in https://stackoverflow.com/questions/34503206/ssl-certificate-verify-failed-error-when-scraping-https-www-thenewboston-co

./Applications/Python\ 3.6/Install\ Certificates.command

7. But now I am stuck at:

....
python3 -m pip install -r requirements.txt

Collecting jsonpickle==1.0.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ca/ce/97404d5aeb58e6155c216825c81b50f6eca8a5345c582317ae48391878f8/jsonpickle-1.0-py2.py3-none-any.whl
...
  Building wheel for python-crfsuite (setup.py) ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/b2/5gjvfk1j1010xptyq4gspmjm000txg/T/pip-install-2av2t1bc/python-crfsuite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/b2/5gjvfk1j1010xptyq4gspmjm000txg/T/pip-wheel-onf3imxh --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/pycrfsuite
  copying pycrfsuite/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/pycrfsuite
  copying pycrfsuite/_dumpparser.py -> build/lib.macosx-10.9-x86_64-3.6/pycrfsuite
  copying pycrfsuite/_logparser.py -> build/lib.macosx-10.9-x86_64-3.6/pycrfsuite
  running build_ext
  building 'pycrfsuite._pycrfsuite' extension
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/pycrfsuite
  creating build/temp.macosx-10.9-x86_64-3.6/crfsuite
  creating build/temp.macosx-10.9-x86_64-3.6/crfsuite/lib
  creating build/temp.macosx-10.9-x86_64-3.6/crfsuite/lib/crf
  creating build/temp.macosx-10.9-x86_64-3.6/crfsuite/lib/crf/src
  creating build/temp.macosx-10.9-x86_64-3.6/crfsuite/swig
  creating build/temp.macosx-10.9-x86_64-3.6/crfsuite/lib/cqdb
  creating build/temp.macosx-10.9-x86_64-3.6/crfsuite/lib/cqdb/src
  creating build/temp.macosx-10.9-x86_64-3.6/liblbfgs
  creating build/temp.macosx-10.9-x86_64-3.6/liblbfgs/lib
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pycrfsuite/_pycrfsuite.cpp -o build/temp.macosx-10.9-x86_64-3.6/pycrfsuite/_pycrfsuite.o -std=c99
  error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
  error: command 'gcc' failed with exit status 1
...
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/b2/5gjvfk1j1010xptyq4gspmjm000txg/T/pip-install-2av2t1bc/python-crfsuite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/b2/5gjvfk1j1010xptyq4gspmjm000txg/T/pip-record-bop8uvxg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/b2/5gjvfk1j1010xptyq4gspmjm000txg/T/pip-install-2av2t1bc/python-crfsuite/
CA02MLPC3797:starter-pack-rasa-stack pc3797$ 

8. However, I am able to move further with spacy with English language submodule

python3 -m spacy download en

9. I have tried to figured whether the advices in the following are relevant or applicable.

a. https://stackoverflow.com/questions/25711122/error-invalid-argument-std-gnu99-not-allowed-with-c-objc
b. https://github.com/scrapinghub/python-crfsuite/issues/47
c. https://github.com/cltk/tutorials/issues/11

Thanks ahead of time.

Philip

**Comment by smpchan** [comment]
A) It appears that downgrade Python to exactly 3.6.4 helps to move way further now. FYI:

https://github.com/scrapinghub/python-crfsuite/issues/69

https://stackoverflow.com/questions/49000674/cython-std-c11-error-using-both-c-and-c

B)
Now the following have no issue:

python3 -m pip install -r requirements.txt
python3 -m spacy download en
python3 -m  pip install -U rasa_core
python3 -m  pip install rasa_nlu[tensorflow]

python3 -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu --project current --verbose

C) Now I encountered some error in training the rasa core:

python3 -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml

...
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so
...

which I presume a MacOS upgrade might help (since my current version is merely (10.11.6)

**Comment by MetcalfeTom** [comment]
Apparently this is a [Pillow error with certain MacOS versions.  ](https://stackoverflow.com/questions/49969800/why-is-pip-installing-pillow-for-os-x-10-12-when-i-have-os-x-10-11-installed/49987984#49987984)Try the following:

`pip install --force-reinstall Pillow==5.0.0`
