### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by bwse** [RasaHQ/starter-pack-rasa-stack#47]
while running `make train-core` it produces error:

> python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/local/lib/python2.7/dist-packages/rasa_core/train.py", line 6, in <module>
>     from rasa_core import config, cli
>   File "/usr/local/lib/python2.7/dist-packages/rasa_core/config.py", line 12
>     def load(config_file: Optional[Text]) -> List['Policy']:
>                         ^
> SyntaxError: invalid syntax
> make: *** [Makefile:31: train-core] Error 1
>

**Comment by oleshy** [comment]
use python3.6.
I did it by changing all commands in Makefile into python3 and installing my dependencies with pip3

**Comment by MetcalfeTom** [comment]
Yup!  `rasa_core` doesn't support python 2 any more. Please make sure to use `python3` in the `make` commands if on Mac
