### ISSUE TITLE
Update stack starter pack to work with Rasa 1.X

### ISSUE THREAD

**Issue by federicotdn** [RasaHQ/starter-pack-rasa-stack#73]
This starter pack should be updated so that it can be used with Rasa versions 1.X and upwards. The `README.md` file should be updated accordingly.

**Comment by erohmensing** [comment]
I would talk to @JustinaPetr and @MetcalfeTom when they get back -- I believe we talked about getting rid of this repo all together. It's leftover from before `rasa init` was a thing and we wanted to help people set up their project directories, but that's taken care of now

**Comment by federicotdn** [comment]
@erohmensing Will do, thanks.

**Comment by tmbo** [comment]
I agree, I will close this for now.
